export const theme = {
  colors: {
    surface: "#F9F9F7",
    onSurface: "#1A1C1A",
    surfaceSecondary: "#FFFFFF",
    onSurfaceSecondary: "#1A1C1A",
    surfaceTertiary: "#EFEFEA",
    onSurfaceTertiary: "#434744",
    surfaceInverse: "#1A1C1A",
    onSurfaceInverse: "#F9F9F7",
    brand: "#4B6955",
    brandPrimary: "#4B6955",
    onBrandPrimary: "#FFFFFF",
    brandSecondary: "#E1E8E3",
    onBrandSecondary: "#2C4033",
    brandTertiary: "#F0F5F2",
    onBrandTertiary: "#3B5241",
    success: "#3A6044",
    onSuccess: "#FFFFFF",
    warning: "#B37A2C",
    onWarning: "#FFFFFF",
    error: "#AA4235",
    onError: "#FFFFFF",
    info: "#5D635E",
    border: "#E6E6E3",
    borderStrong: "#C7C7C2",
    divider: "#EBEBE8",
  },
  spacing: { xs: 4, sm: 8, md: 12, lg: 16, xl: 24, "2xl": 32, "3xl": 48 },
  radius: { sm: 6, md: 12, lg: 20, pill: 999 },
  font: {
    display: "PlusJakartaSans",
    text: "PlusJakartaSans",
    numeric: "SpaceGrotesk",
  },
  fontSize: { sm: 12, base: 14, lg: 16, xl: 20, "2xl": 24, "3xl": 32 },
};

export type Theme = typeof theme;
